### ISSUE TITLE
Include super-awesome builds from AdoptOpenJDK

### ISSUE THREAD

**Issue by x80486** [halcyon/asdf-java#1]
[AdoptOpenJDK](https://adoptopenjdk.net/index.html) now also distributes OpenJDK upstream builds, although this set don't have support for all the platforms.

**Comment by WhiteVermouth** [comment]
Maybe you can try my [fork](https://github.com/WhiteVermouth/asdf-java), which supports zulu, adoptopenjdk and amazon corretto, but oracle jdk support is removed.

**Comment by halcyon** [comment]
I still have some work to do on adoptopenjdk support to make it work with Mac as well.

**Comment by halcyon** [comment]
Please check out my rewrite of the plugin - it uses AdoptOpenJDK's API, and includes corretto/zulu.
https://github.com/halcyon/asdf-java-2
@x80486 @WhiteVermouth @mig4 Looking forward to feedback!

**Comment by halcyon** [comment]
Now all AdoptOpenJDK builds are available here. I've merged in all changes in the new architecture developed in `asdf-java-2` to `asdf-java`.
@x80486 @WhiteVermouth @mig4
