### ISSUE TITLE
Add Zulu OpenJDK for MacOS ARM to the list

### ISSUE THREAD

**Issue by nyang** [halcyon/asdf-java#115]
Pls check this for details: https://www.azul.com/downloads/zulu-community/?os=macos&architecture=arm-64-bit&package=jdk

and: https://docs.azul.com/zulu/zulurelnotes/ZuluReleaseNotes/ReleaseDetails_macos_Apple_Silicon_November2020.htm

**Comment by bric3** [comment]
I think this should be reported on https://github.com/joschi/java-metadata

**Comment by nyang** [comment]
> I think this should be reported on https://github.com/joschi/java-metadata

Thanks for reply. I didnt notice that all the metedata is based on [java-metadata](https://github.com/joschi/java-metadata). Sorry about that. 

After I checked on the logical of java-metadata, right now it parses the https://static.azul.com/zulu/bin/ page to get data, and that project has an issue logged in order to migrating to https://www.azul.com/downloads/zulu-community/api/ ([issue 4](https://github.com/joschi/java-metadata/issues/4)), but unfortunately neither of them updated with the ARM based JDK. 

So, I guess so far we could only download from Zulu's website. 

Thanks again!
