### ISSUE TITLE
add alibaba dragonwell jdk

### ISSUE THREAD

**Issue by hoangtranwork** [halcyon/asdf-java#122]
Alibaba has their own openjdk based JDK - Dragonwell (8 & 11). They only support linux x64. If possible please add it. Thank you. 

Ref:
https://alibaba-cloud.medium.com/reshaping-the-java-language-on-the-cloud-c8342bfa94fa
https://github.com/alibaba/dragonwell11/releases

**Comment by joschi** [comment]
Dragonwell 8 and 11 should already be supported with the latest version of asdf-java:

https://github.com/halcyon/asdf-java/blob/0514c7f2d8c57666d59feda8fc1fb3c6b45ab89b/data/jdk-linux-x86_64.tsv#L176-L184

**Comment by hoangtranwork** [comment]
Thank you very much. This issue should be closed.
