### ISSUE TITLE
Unable to check sha256sum for any java install

### ISSUE THREAD

**Issue by gurpreet3737** [halcyon/asdf-java#124]
after installing java successfully, bash shows this error message: **"sha256sum: standard input: no properly formatted SHA256 checksum lines found"**.

OS specifications:
Debian Buster/Debian-10 with up-to-date patches.
coreutils ver:8.30-3.

**Comment by xalvarez** [comment]
I could reproduce the same issue with a fresh Ubuntu 18.04 installation with all updates installed.

**Comment by joschi** [comment]
@xalvarez @gurpreet3737 Does the problem still exist on your machines?

I'm unable to reproduce this issue in a Docker container running Ubuntu 20.04:
```
root@88ef7bb34e13:/# asdf info
OS:
Linux 88ef7bb34e13 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.0-c6145d0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/root/.asdf

Oohes nooes ~! No plugins installed
ASDF INSTALLED PLUGINS:


root@88ef7bb34e13:/# asdf plugin-add java
initializing plugin repository...
Cloning into '/root/.asdf/repository'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 2848 (delta 22), reused 17 (delta 6), pack-reused 2806
Receiving objects: 100% (2848/2848), 667.67 KiB | 2.87 MiB/s, done.
Resolving deltas: 100% (1384/1384), done.
root@88ef7bb34e13:/# asdf list-all java
adoptopenjdk-8.0.162+12.openj9-0.8.0
[...]
zulu-musl-15.29.15
root@88ef7bb34e13:/# asdf install java adoptopenjdk-15.0.2+7
######################################################## 100.0%
OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz
OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz: OK
root@88ef7bb34e13:/# asdf global java adoptopenjdk-15.0.2+7
root@88ef7bb34e13:/# java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

**Comment by joschi** [comment]
It looks like there were some checksums missing in the data file(s) until https://github.com/halcyon/asdf-java/commit/511aca4f7c46b26202f3139dfe336f8b5a8fd21b#diff-9ca415b8219a52bbc6b30cf35df4819d5f03ef2b167bf4b5f0522602619f7fd2

Maybe you were trying to install one of the affected JDKs?

**Comment by xalvarez** [comment]
Hi @joschi, I'm no longer able to reproduce the issue. I agree, it was probably caused by the missing checksums.

**Comment by gurpreet3737** [comment]
I was installing zulu-javafx openjdk builds version 8 and 11. I manually verified checksums for them from their website. Thanks for the replies by all the participants.
