### ISSUE TITLE
Shell stuck in java directory

### ISSUE THREAD

**Issue by iatanas0v** [halcyon/asdf-java#130]
After updating the java plugin I noticed that my shell is stuck in the `~/.asdf/installs/java/openjdk-12/bin`. In fact it gets stuck in the current active version (in my case openjdk-12). I'm running fish shell (v3.1.2).

Just to elaborate what "stuck" means; Issueing `cd ..`, `cd ~/` or `cd /`, pretty much any attempt to navigate results in shell staying at the java bin directory.

I tried checking out different versions of java plugin and the last working version was 132ca502b124c3ebbfea565aa8c65f874c88524c , meaning the problematic PR should be https://github.com/halcyon/asdf-java/pull/114

I checked the code but I can't pinpoint the issue. I'll be more than happy to test some code for you

**Comment by gnfisher** [comment]
I reverted to using `realpath` in the `set-java-home.fish` script and it works as expected. I wasn't sure why `realpath` was replaced, the linked PR doesn't specify why. Without understanding fully why that choice was made I am hesitant to put up a PR reversing it.

**Comment by CodingAnarchy** [comment]
`realpath` is a fish builtin, so it should have always been used instead of the custom function, which absolutely does not work on `fish`.
