### ISSUE TITLE
I cannot see openJDK versions after update

### ISSUE THREAD

**Issue by maxan** [halcyon/asdf-java#14]
Hi! I updated my plug-in version and I just can see the versions:

> amazon-corretto-11.0.3.7.1
> amazon-corretto-8.212.04.2
> azul-zulu-11.0.3
> azul-zulu-12.0.1
> azul-zulu-7u222
> azul-zulu-8.0.212

(result of "list-all" command)

I installed all requirements here (jq, sha256sum and curl). I'm using Linux Mint 19.2.

Thanks :)

**Comment by halcyon** [comment]
Could you try running `~/.asdf/plugins/java/bin/list-all` and post the output?

**Comment by halcyon** [comment]
I think I know what happened. Please delete all files in /tmp/asdf-java.cache

**Comment by maxan** [comment]
Yeah! Now it's listing:

> adopt-openjdk-10.0.2+13
> adopt-openjdk-10.0.2+13.1
> adopt-openjdk-11+28
> adopt-openjdk-11.0.1+13
> adopt-openjdk-11.0.2+7
> adopt-openjdk-11.0.2+9
> adopt-openjdk-11.0.3+7
> adopt-openjdk-11.0.4+11
> adopt-openjdk-11.0.4+11.2
> adopt-openjdk-11.0.4+11.4
> adopt-openjdk-12+33
> adopt-openjdk-12.0.1+12
> adopt-openjdk-12.0.2+10
> adopt-openjdk-12.0.2+10.2
> adopt-openjdk-8u172-b11
> adopt-openjdk-8u181-b13
> adopt-openjdk-8u191-b12
> adopt-openjdk-8u192-b12
> adopt-openjdk-8u202-b08
> adopt-openjdk-8u212-b03
> adopt-openjdk-8u212-b04
> adopt-openjdk-8u222-b10
> adopt-openjdk-9+181
> adopt-openjdk-9.0.4+11
> amazon-corretto-11.0.3.7.1
> amazon-corretto-8.212.04.2
> azul-zulu-11.0.3
> azul-zulu-12.0.1
> azul-zulu-7u222
> azul-zulu-8.0.212
> adopt-openjdk-10.0.2+13_openj9-0.9.0
> adopt-openjdk-11.0.2+9_openj9-0.12.1
> adopt-openjdk-11.0.3+7_openj9-0.14.0
> adopt-openjdk-11.0.3+7_openj9-0.14.3
> adopt-openjdk-11.0.4+11.2_openj9-0.15.1
> adopt-openjdk-11.0.4+11.4_openj9-0.15.1
> adopt-openjdk-11.0.4+11_openj9-0.15.1
> adopt-openjdk-12+33_openj9-0.13.0
> adopt-openjdk-12.0.1+12_openj9-0.14.1
> adopt-openjdk-12.0.2+10.2_openj9-0.15.1
> adopt-openjdk-12.0.2+10_openj9-0.15.1
> adopt-openjdk-8u162-b12_openj9-0.8.0
> adopt-openjdk-8u181-b13_openj9-0.9.0
> adopt-openjdk-8u192-b12_openj9-0.11.0
> adopt-openjdk-8u202-b08_openj9-0.12.1
> adopt-openjdk-8u212-b03_openj9-0.14.0
> adopt-openjdk-8u212-b04_openj9-0.14.2
> adopt-openjdk-8u222-b10_openj9-0.15.1
> adopt-openjdk-9.0.4+12_openj9-0.9.0
> adopt-openjdk-11.0.2+9_openj9-0.12.1_large-heap
> adopt-openjdk-11.0.3+7_openj9-0.14.0_large-heap
> adopt-openjdk-11.0.3+7_openj9-0.14.3_large-heap
> adopt-openjdk-11.0.4+11.2_openj9-0.15.1_large-heap
> adopt-openjdk-11.0.4+11.4_openj9-0.15.1_large-heap
> adopt-openjdk-11.0.4+11_openj9-0.15.1_large-heap
> adopt-openjdk-12+33_openj9-0.13.0_large-heap
> adopt-openjdk-12.0.1+12_openj9-0.14.1_large-heap
> adopt-openjdk-12.0.2+10.2_openj9-0.15.1_large-heap
> adopt-openjdk-12.0.2+10_openj9-0.15.1_large-heap
> adopt-openjdk-8u181-b13_openj9-0.9.0_large-heap
> adopt-openjdk-8u192-b12_openj9-0.11.0_large-heap
> adopt-openjdk-8u202-b08_openj9-0.12.1_large-heap
> adopt-openjdk-8u212-b03_openj9-0.14.0_large-heap
> adopt-openjdk-8u212-b04_openj9-0.14.2_large-heap
> adopt-openjdk-8u222-b10_openj9-0.15.1_large-heap

I think it's OK now.

Thanks, @halcyon
