### ISSUE TITLE
IntelliJ IDEA 2021.1 supports JDKs installed by asdf-java

### ISSUE THREAD

**Issue by joschi** [halcyon/asdf-java#145]
Not really an issue, bug report, or feature request.

I just wanted to leave this here. 😉

![Tweet about asdf-java support in IntelliJ IDEA 2021.1](https://user-images.githubusercontent.com/43951/113912384-55ea9100-97db-11eb-9eec-45a32fcc7b0a.png)
Tweet: https://twitter.com/_asdf_vm/status/1379854390840979457

**Comment by myjohndoeside** [comment]
Can somebody confirm that this still works in 2022.1.1 release?
Mine doesn't display any of the JDKs installed by asdf, I still have to manually add them.

Or is there a specific asdf command that I need to run first?

**Comment by joschi** [comment]
@myjohndoeside See https://youtrack.jetbrains.com/issue/IDEA-292847 and https://github.com/JetBrains/intellij-community/pull/2031.

**Comment by myjohndoeside** [comment]
Thank you, I must've missed it when I first encountered this problem couple days ago.

I'm curious, when IntelliJ does detect the asdf JDK installation, does it automatically respect the global configuration set by asdf or do I still need to set it manually? I must say it is unlike what I've experienced with Node.js environment where this thing is pretty straight forward.

**Comment by muescha** [comment]
it should automatic detect the directory under `~/.asdf/installs` but there was a regression in one commit 

until the fix is published: see the workaround in the issue / pull request with setting the environment variable

**Comment by myjohndoeside** [comment]
@muescha Thanks for spotting the mistake and sending the fix so quickly!

Are you familiar with the release cycle of IntelliJ? Will we receive this patch in regular channel anytime soon?
