### ISSUE TITLE
No compatible versions available

### ISSUE THREAD

**Issue by superganplus** [halcyon/asdf-java#173]
I already installed this plugin, 

and run script: `asdf list all java`, 

return: `No compatible versions available (java ) `

I checked about ASDF env info :
OS:
Darwin 192.168.0.101 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/usr/local/opt/asdf/libexec

ASDF INSTALLED PLUGINS:
java                         https://github.com/halcyon/asdf-java.git master 754b212
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master ed34355

And checked others:
1. `arch`: i386
2. `uname -m`: x86_64
3. `uname -v`: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64

**I don't know what the problem is...**

THANKS.

**Comment by Jooaomar** [comment]
I have the same problem :/

**Comment by superganplus** [comment]
The reason is that you can't visit the address: `https://raw.githubusercontent.com`

I found a way to fixed this problem：

Edit file:`~/.asdf/plugins/java/bin/functions`.

use text `cp "${HOME}/.asdf/plugins/java/data//jdk-${OS}-${ARCHITECTURE}.tsv"  "${cache_file}"` to replace about the 55 line:`curl -s -f --compressed -L "https://raw.githubusercontent.com/halcyon/asdf-java/master/data/jdk-${OS}-${ARCHITECTURE}.tsv" -o "${cache_file}"`


save file and retry cmd: `asdf list all java`
you will see a list of Java that can be installed, and then select a version to install, 
such as: `asdf install java adoptopenjdk-8.0.322+6`



good luck guys.

**Comment by danielporto** [comment]
I don't think the issue is closed. I'm having the same issue.
Surprisingly, two users in the same machine has a different outcome of the same command
with the same version.
One list all java packages. The other does not.

**Comment by danielporto** [comment]
As an update, I noticed that the only difference in both profiles is the version of the java plugin.
broken env:
```
asdf info
OS:
Linux inesc-oc8 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/XXXXX/.asdf

ASDF INSTALLED PLUGINS:
java                         https://github.com/halcyon/asdf-java.git master 21b1c9a

```

working env:
```
asdf info
OS:
Linux inesc-oc8 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.10.2-7e7a1fa

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/YYYY/.asdf

ASDF INSTALLED PLUGINS:
golang                       https://github.com/kennyp/asdf-golang.git master 9480360
gradle                       https://github.com/rfrancis/asdf-gradle.git master 34e1e36
java                         https://github.com/halcyon/asdf-java.git master 38d917e
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master cd8dc32
python                       https://github.com/danhper/asdf-python.git master b544ac9

```

**Comment by danielporto** [comment]
Ok a final follow up:
I ran on the broken profile:
```
asdf plugin update java 38d917e
````

and it fixed the issue. 
The current version of the plugin is broken.

**Comment by vraravam** [comment]
This problem still persists with the latest released version of asdf. I tried the command to update to a particular sha of the java plugin as described above, and the output I get is:
```
Plugin java's list-all callback script failed with output:

Unknown machine architecture: arm64
```
Did this plugin lose support for mac m1 machines recently?

**Comment by vraravam** [comment]
update: the m1 machine started working, but the x86 is now broken - with the `38d917e` version of the java plugin

**Comment by vraravam** [comment]
Again broken on the m1  mac.

**Comment by rschmitt** [comment]
My machine reports `arm64` as the architecture (`uname -m`), but the [TSV files](https://github.com/halcyon/asdf-java/commit/a05b02c9d7bcd8648a467d2dd81f785863d0cc35) in the Java plugin have `aarch64` in the name. Renaming the files in `~/.asdf/plugins/java` from `*aarch64*` to `*arm64*` fixes the problem. Something is off here.

**Comment by rschmitt** [comment]
I worked around this by migrating to [rtx](https://github.com/jdxcode/rtx).

**Comment by vraravam** [comment]
Thanks for the pointer @rschmitt - I have also switched to `rtx`!

**Comment by jdxcode** [comment]
this plugin is full of issues I've documented here: https://github.com/jdxcode/rtx/issues/403

a lot of these are already fixed by rtx but I plan to fix the rest of them today in rtx-java.

**Comment by ljak** [comment]
I got a lot of errors described in this thread due to problems with the default installation of `curl` on Ubuntu 20.04 on my new Dell computer (Latitude 7430). Removing `curl` and re-installing solves those issues.

**Comment by AshutoshSajan** [comment]
facing the same issue on Ubuntu

OS:
Linux Ashu 5.15.0-87-generic #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
zsh 5.8 (x86_64-ubuntu-linux-gnu)

BASH VERSION:
5.0.17(1)-release

ASDF VERSION:
v0.13.1-0586b37

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/home/ashu/.asdf
ASDF_DIR=/home/ashu/.asdf
ASDF_CONFIG_FILE=/home/ashu/.asdfrc

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master a4c42e1
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 6744df7
golang                       https://github.com/kennyp/asdf-golang.git master 33b1f6d
java                         https://github.com/halcyon/asdf-java.git master d077fb8
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 9c4e0f2

**Comment by dvlp123456** [comment]
I got the same problem, my environment information like this:

`[~]$ asdf info
OS:
Darwin MacBook-Pro-XXXXX.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.0)

BASH VERSION:
3.2.57(1)-release

ASDF VERSION:
v0.12.0

ASDF INTERNAL VARIABLES:
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=.tool-versions
ASDF_DATA_DIR=/Users/XXXXX/.asdf
ASDF_DIR=/usr/local/opt/asdf/libexec
ASDF_CONFIG_FILE=/Users/XXXXX/.asdfrc

ASDF INSTALLED PLUGINS:
elixir                       https://github.com/asdf-vm/asdf-elixir.git master d08f506
erlang                       https://github.com/asdf-vm/asdf-erlang.git master 0463971
golang                       https://github.com/kennyp/asdf-golang.git master cc8bc47
java                         https://github.com/halcyon/asdf-java.git master ff53e69
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master 05f99c3
pnpm                         https://github.com/jonathanmorley/asdf-pnpm.git master 95752a9
postgres                     https://github.com/smashedtoatoms/asdf-postgres.git master b44003f
python                       https://github.com/danhper/asdf-python.git master 8d321f7`

the error information like this:

`
[~]$ asdf list-all elixir
No compatible versions available (elixir )
`

my solution is to update the plugin: `asdf plugin-update elixir`

finally, successful information:

`
[~]$ asdf list-all elixir
0.12.4
0.12.5
0.13.0
...
`
