### ISSUE TITLE
Oracle JDK 22 / GraalVM 22 aren't available to download

### ISSUE THREAD

**Issue by donbeave** [halcyon/asdf-java#223]
Oracle already released JDK 22 / GraalVM 22, it's available to download: 

https://www.oracle.com/java/technologies/downloads/#java22
https://www.oracle.com/java/technologies/downloads/#graalvmjava22

But it's not available in the asdf-java plugin, only GraalVM 21 is available:

```bash
asdf list-all java
```

Here is a list of what I can see:

```
oracle-17
oracle-17.0.1
oracle-17.0.2
oracle-17.0.3
oracle-17.0.3.1
oracle-17.0.4
oracle-17.0.4.1
oracle-17.0.5
oracle-17.0.6
oracle-17.0.7
oracle-17.0.8
oracle-17.0.9
oracle-17.0.10
oracle-18
oracle-18.0.1
oracle-18.0.1.1
oracle-18.0.2
oracle-18.0.2.1
oracle-19
oracle-19.0.1
oracle-19.0.2
oracle-20
oracle-20.0.1
oracle-20.0.2
oracle-21
oracle-21.0.1
oracle-21.0.2
oracle-graalvm-17.0.7
oracle-graalvm-17.0.8
oracle-graalvm-17.0.9
oracle-graalvm-17.0.10
oracle-graalvm-20.0.1
oracle-graalvm-20.0.2
oracle-graalvm-21
oracle-graalvm-21.0.1
oracle-graalvm-21.0.2
```

**Comment by joschi** [comment]
This has been fixed since https://github.com/halcyon/asdf-java/commit/7e07ff69c7445b88eb8204acb6a05adc9dc80a4.

**Comment by donbeave** [comment]
@joschi Thank you so much!
