### ISSUE TITLE
MacOS support for /usr/libexec/java_home

### ISSUE THREAD

**Issue by johnjelinek** [halcyon/asdf-java#33]
MacOS has a convention of using `/usr/libexec/java_home` to list installed JVMs/JDKs. Instead of overwriting `JAVA_HOME`, can we make use of `/usr/libexec/java_home` instead? Perhaps a symlink can be added in here: `/Library/Java/JavaVirtualMachines/`.

**Comment by johnjelinek** [comment]
Same as: https://github.com/skotchpine/asdf-java/issues/39

**Comment by johnjelinek** [comment]
```
> "$PWD"
/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents
```

**Comment by halcyon** [comment]
@johnjelinek 
I like the idea of making asdf-java more compatible with the way MacOS works. Would one need root privileges to write symlinks to these locations? If that's accurate, how would you propose handling that?

PRs welcome!

**Comment by johnjelinek** [comment]
Yes, it'll require . `sudo` to do the symlink. Does `asdf` offer the ability to accept a password when `sudo` is needed, like `homebrew` does?

**Comment by halcyon** [comment]
I don't know, also Mac is not an easy platform for me to test on - is this something you could look into?

**Comment by fcrespo82** [comment]
Any news on this? I am willing to help with the PR if there still interest in adding such functionality.
