### ISSUE TITLE
Problems installing Java oracle-8.191

### ISSUE THREAD

**Issue by daincredibleholg** [halcyon/asdf-java#41]
It does look like the JDK 8u191 from Oracle has moved?
Here is the output I get:

```
asdf install java oracle-8.191
░asdf java :)░ downloading http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-macosx-x64.dmg
####################################################################################################################################################################################################################################### 100.0% #=O=#      #         #
curl: (22) The requested URL returned error: 404 Not Found
░asdf java :(░ asdf java failed. downloading java dist
```

Interestingly enough, the version _oracle-8.191_ is afterwards "installed", I have to _uninstall_ it via `asdf uninstall oracle-8.191` which returns gracefully with a success.

**Comment by halcyon** [comment]
Because Oracle regularly cut off unauthenticated access to their downloads, current versions of asdf-java do not directly support installation of Oracle versions of the JDK. Most needs can be met with the adopt-openjdk versions. You could also manually install an Oracle version of the JDK.

**Comment by halcyon** [comment]
Yes, I too have observed the lack of error handling for failed installations. PRs which would fix this are welcome!

**Comment by halcyon** [comment]
Please run asdf plugin-update java
