### ISSUE TITLE
Add support for "latest" versions

### ISSUE THREAD

**Issue by aheritier** [halcyon/asdf-java#46]
With asdf 0.7.6 it is possible to use the `latest` keyword to install a tool and there is a new `latest` command to display the latest version available

https://asdf-vm.com/#/changelog?id=_076

Because the version is also used for the distribution using only the `latest` keyword could be strange but it could be useful with at least a distribution name and version prefix

```
  asdf install java latest # Not sure what it could do here...
  asdf install java latest:adopt-openjdk # installs latest Java version from adopt-openjdk
  asdf install java latest:adopt-openjdk-11 # installs latest Java 11.x version from adopt-openjdk
  asdf latest java # Not sure what it could do here...
  asdf latest java adopt-openjdk # displays latest Java version from adopt-openjdk
  asdf latest java adopt-openjdk-11 # displays latest Java 11.x version from adopt-openjdk
```

**Comment by joschi** [comment]
@aheritier Most of the commands are already working with asdf-vm 0.7.6 and the current `master` of asdf-java:
```
# asdf version
v0.7.6

# asdf latest java azul
azul-zulu-13.29.9-jdk13.0.2

# asdf latest java amaz
amazon-corretto-11.0.6.10.1-2

# asdf latest java adopt-openjdk-11
adopt-openjdk-11.0.6+10_openj9-0.18.1_large-heap

# asdf install java latest:amazon
################################# 100,0%
amazon-corretto-11.0.6.10.1-2-macosx-x64.tar.gz
################################# 100,0%
amazon-corretto-11.0.6.10.1-2-macosx-x64.tar.gz.sha256.txt
amazon-corretto-11.0.6.10.1-2-macosx-x64.tar.gz: OK
```

I'm also not sure if there would be a good default for `asdf latest java` and `asdf install java latest`.

**Comment by aheritier** [comment]
great @joschi 
It's just a bit annoying that something like `asdf latest java adopt-openjdk-11` is installing the version with `openj9` and `large-heap`. I would imagine that the majority of developers are expecting to use the default one (`adopt-openjdk-11.0.6+10` today)

Not sure if it is something which could be changed.

**Comment by joschi** [comment]
> It's just a bit annoying that something like asdf latest java adopt-openjdk-11 is installing the version with openj9 and large-heap.

Yes, indeed it is. That's because of how the latest version is selected, by sorting the output of `list-all` by version (something like `sort -V`) and selecting the last version in that sort order. This unfortunately puts `adopt-openjdk-11.0.6+10_openj9-0.18.1_large-heap` after `adopt-openjdk-11.0.6+10`.

```
# asdf list-all java adopt-openjdk-11
adopt-openjdk-11+28
adopt-openjdk-11.0.1+13
adopt-openjdk-11.0.2+7
adopt-openjdk-11.0.2+9
adopt-openjdk-11.0.3+7
adopt-openjdk-11.0.4+11
adopt-openjdk-11.0.4+11.2
adopt-openjdk-11.0.4+11.4
adopt-openjdk-11.0.5+10
adopt-openjdk-11.0.6+10
adopt-openjdk-11.0.2+9_openj9-0.12.1
adopt-openjdk-11.0.3+7_openj9-0.14.0
adopt-openjdk-11.0.3+7_openj9-0.14.3
adopt-openjdk-11.0.4+11.2_openj9-0.15.1
adopt-openjdk-11.0.4+11.4_openj9-0.15.1
adopt-openjdk-11.0.4+11_openj9-0.15.1
adopt-openjdk-11.0.5+10.1_openj9-0.17.0
adopt-openjdk-11.0.5+10_openj9-0.17.0
adopt-openjdk-11.0.6+10_openj9-0.18.0
adopt-openjdk-11.0.6+10_openj9-0.18.1
adopt-openjdk-11.0.2+9_openj9-0.12.1_large-heap
adopt-openjdk-11.0.3+7_openj9-0.14.0_large-heap
adopt-openjdk-11.0.3+7_openj9-0.14.3_large-heap
adopt-openjdk-11.0.4+11.2_openj9-0.15.1_large-heap
adopt-openjdk-11.0.4+11.4_openj9-0.15.1_large-heap
adopt-openjdk-11.0.4+11_openj9-0.15.1_large-heap
adopt-openjdk-11.0.5+10.1_openj9-0.17.0_large-heap
adopt-openjdk-11.0.5+10_openj9-0.17.0_large-heap
adopt-openjdk-11.0.6+10_openj9-0.18.0_large-heap
adopt-openjdk-11.0.6+10_openj9-0.18.1_large-heap
```

**Comment by aheritier** [comment]
Don't you think @joschi that it could eb a good idea to ask to asdf to add a notion of "variant" ?
I may suppose that we could not be the only community where it could be useful.
Variants could be useful to select the platform (intel vs ARM or 32 vs 64b in the past).

**Comment by aheritier** [comment]
@halcyon @delgurth 

With this fix I get

```
asdf list-all java adoptopenjdk-11
adoptopenjdk-11.0.0+28
adoptopenjdk-11.0.1+13
adoptopenjdk-11.0.1+13.openj9-0.11.0
adoptopenjdk-11.0.2+7
adoptopenjdk-11.0.2+9
adoptopenjdk-11.0.2+9.openj9-0.12.0
adoptopenjdk-11.0.2+9.openj9-0.12.1
adoptopenjdk-11.0.3+7
adoptopenjdk-11.0.3+7.openj9-0.14.0
adoptopenjdk-11.0.3+7.openj9-0.14.3
adoptopenjdk-11.0.4+11.1
adoptopenjdk-11.0.4+11.1.openj9-0.15.1
adoptopenjdk-11.0.5+10.1
adoptopenjdk-11.0.5+10.1.openj9-0.17.0
adoptopenjdk-11.0.6+10.1
adoptopenjdk-11.0.6+10.1.openj9-0.18.0
adoptopenjdk-11.0.6+10.1.openj9-0.18.1
adoptopenjdk-11.0.7+10.1
adoptopenjdk-11.0.7+10.1.openj9-0.20.0
adoptopenjdk-11.0.8+10
adoptopenjdk-11.0.8+10.openj9-0.21.0
adoptopenjdk-11.0.9+11
adoptopenjdk-11.0.9+11.openj9-0.23.0
adoptopenjdk-11.0.9+101
adoptopenjdk-11.0.10+9
adoptopenjdk-11.0.10+9.openj9-0.24.0
```

it's ok

but

```
asdf latest java adoptopenjdk-11
adoptopenjdk-11.0.10+9.openj9-0.24.0
```

Is there a hack to not get the openj9 distro ?

**Comment by delgurth** [comment]
@aheritier you need to wait till the next update run. It's scheduled in a few hours. See: https://github.com/halcyon/asdf-java/actions/workflows/update-data.yaml

**Comment by aheritier** [comment]
awesome @delgurth 
Thanks a lot for you work

**Comment by delgurth** [comment]
@aheritier 

For me it now  works as expected:

```
❯ asdf latest java adoptopenjdk-11
adoptopenjdk-11.0.10+9
❯ asdf latest java adoptopenjdk-openj9-11
adoptopenjdk-openj9-11.0.10+9.openj9-0.24.0
```

**Comment by aheritier** [comment]
@delgurth just tested it and I confirm.
Thanks a lot, it's a very useful fix
