### ISSUE TITLE
Support /usr/libexec/java_home for installs

### ISSUE THREAD

**Issue by daincredibleholg** [halcyon/asdf-java#53]
I just had a hard time to figure that out:
When I try to run anything Eclipse-based (in this case, Apache Directory Studio) and I do not have a "proper" Java installation (one that does not end up in /Library/Java/JavaFrameworks and has all the Info.plist and other foo), MacOS presents me with an error message. This error message only tells me to install legacy Java.

So, it would be great if installing a version via this plugin would create the symlinks or meta-information needed so that java_home "just" picks up the available versions. The benefit would be that applications like ADS or Eclipse would run out of the box.

Spoilers: Following up search results on how to fix this manually point to the Eclipse Info.plist. Unfortunately, configuring the `-vm` flag doesn't help.

**Comment by joschi** [comment]
Duplicate of #33.

**Comment by daincredibleholg** [comment]
Mea culpa! Will follow the other one and we close this one :)
