### ISSUE TITLE
SDKMan?

### ISSUE THREAD

**Issue by cricket007** [halcyon/asdf-java#70]
This tool seems to have overlap

Maybe reach out to some people over here?  https://github.com/sdkman/sdkman-cli

**Comment by joschi** [comment]
SDKMAN! has some overlap with asdf-vm, that's correct.

In contrast to asdf-vm, SDKMAN! doesn't support plugins (such as asdf-java) and the list of supported Java and tools versions are maintained manually whereas with asdf-vm that's most of the time not the case.

Both tools do a good job, it's more a question of which you prefer. From a technical perspective, there's not much we can use from the code of SDKMAN! in asdf-java.

**Comment by cricket007** [comment]
Makes sense, thanks!
