### ISSUE TITLE
OpenJDK not available for version higher than 9

### ISSUE THREAD

**Issue by lhauspie** [halcyon/asdf-java#71]
I already installed 2 different versions of java on my laptop with asdf in the past: 
```bash
[18:07:18] lhauspie@997H8H2:~/projects/perso(master)$ asdf global java adopt-openjdk-1<tab><tab>
adopt-openjdk-12.0.2+10  adopt-openjdk-13.0.2+8   
```

But when I ask asdf to install a new version of Java, I don't find any version of OpenJDK higher than jdk9:
```bash
[18:27:19] lhauspie@997H8H2:~/.asdf/plugins/java(master)$ asdf install java <tab><tab>
amazon-corretto-11.0.3.7.1               azul-zulu-11.31.11-jdk11.0.3             azul-zulu-8.42.0.21-jdk8.0.232           jdk8u192-b12_openj9-0.11.0               jdk8u232-b09.1_openj9-0.17.0_large-heap
amazon-corretto-11.0.4.11.1              azul-zulu-11.35.13-jdk11.0.5             azul-zulu-8.42.0.23-jdk8.0.232           jdk8u192-b12_openj9-0.11.0_large-heap    jdk8u232-b09_openj9-0.17.0
amazon-corretto-11.0.5.10.1              azul-zulu-11.35.15-jdk11.0.5             azul-zulu-8.44.0.11-jdk8.0.242           jdk8u202-b08_openj9-0.12.1               jdk8u232-b09_openj9-0.17.0_large-heap
amazon-corretto-11.0.5.10.2              azul-zulu-11.37.17-jdk11.0.6             azul-zulu-8.44.0.9-jdk8.0.242            jdk8u202-b08_openj9-0.12.1_large-heap    jdk8u242-b08_openj9-0.18.1
amazon-corretto-11.0.6.10.1              azul-zulu-12.2.3-jdk12.0.1               azul-zulufx-11.35.15-jdk11.0.5           jdk8u212-b03_openj9-0.14.0               jdk8u242-b08_openj9-0.18.1_large-heap
amazon-corretto-11.0.6.10.1-2            azul-zulu-13.27.9-jdk13                  azul-zulufx-11.37.19-jdk11.0.6           jdk8u212-b03_openj9-0.14.0_large-heap    jdk-9.0.4+12_openj9-0.9.0
amazon-corretto-8.212.04.2               azul-zulu-13.28.11-jdk13.0.1             azul-zulufx-8.42.0.23-jdk8.0.232         jdk8u212-b04_openj9-0.14.2               sapmachine-11.0.6
amazon-corretto-8.232.09.1               azul-zulu-13.29.9-jdk13.0.2              azul-zulufx-8.44.0.13-jdk8.0.242         jdk8u212-b04_openj9-0.14.2_large-heap    sapmachine-11.0.6.0.1
amazon-corretto-8.232.09.2               azul-zulu-7.29.0.5-jdk7.0.222            jdk8u162-b12_openj9-0.8.0                jdk8u222-b10_openj9-0.15.1               sapmachine-13.0.2
amazon-corretto-8.242.07.1               azul-zulu-7.34.0.5-jdk7.0.242            jdk8u181-b13_openj9-0.9.0                jdk8u222-b10_openj9-0.15.1_large-heap    sapmachine-14
amazon-corretto-8.242.08.1               azul-zulu-7.36.0.5-jdk7.0.252            jdk8u181-b13_openj9-0.9.0_large-heap     jdk8u232-b09.1_openj9-0.17.0             
```

And when I still trying to install a version not listed here, I have an error:
```bash
[18:32:24] lhauspie@997H8H2:~/.asdf/plugins/java(master)$ asdf install java adopt-openjdk-13.0.2+8
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information
```

I also tried to install a OpenJDK version listed above, but nothing works:
```bash
[18:49:33] lhauspie@997H8H2:~/projects/perso/cqrs-exploration/cqrs-microservice-sampler(master)$ asdf install java jdk8u242-b08_openj9-0.18.1
curl: Remote file name has no length!
curl: try 'curl --help' or 'curl --manual' for more information
```

And the plugin have been correctly updated:
```bash
[18:42:41] lhauspie@997H8H2:~/.asdf/plugins/java(master)$ asdf plugin update java
Updating java...
Déjà sur 'master'
Votre branche est à jour avec 'origin/master'.
[18:42:42] lhauspie@997H8H2:~/.asdf/plugins/java(master)$ git log --oneline
e5391ad (HEAD -> master, origin/master, origin/HEAD) JDK 14
```

As I'm on linux (Ubuntu) with an x64 architecture, I tried to list the OpenJDK versions 10, 11, 12 and 13 by reaching these v3 API urls, and they all returned at least one result, so what's going wrong ?

https://api.adoptopenjdk.net/v3/assets/feature_releases/10/ga?architecture=x64&os=linux&image_type=jdk&page=0&page_size=100&project=jdk&sort_order=ASC&vendor=adoptopenjdk
https://api.adoptopenjdk.net/v3/assets/feature_releases/11/ga?architecture=x64&os=linux&image_type=jdk&page=0&page_size=100&project=jdk&sort_order=ASC&vendor=adoptopenjdk
https://api.adoptopenjdk.net/v3/assets/feature_releases/12/ga?architecture=x64&os=linux&image_type=jdk&page=0&page_size=100&project=jdk&sort_order=ASC&vendor=adoptopenjdk
https://api.adoptopenjdk.net/v3/assets/feature_releases/13/ga?architecture=x64&os=linux&image_type=jdk&page=0&page_size=100&project=jdk&sort_order=ASC&vendor=adoptopenjdk

Thanks in advance.

**Comment by joschi** [comment]
I've opened a bug report for this inconsistency at the AdoptOpenJDK project.

AdoptOpenJDK/openjdk-api-v3#171

**Comment by rubencaro** [comment]
@halcyon I think people in https://github.com/halcyon/asdf-java/issues/72 is right.

Any quick workaround we can use while waiting for @AdoptOpenJDK to respond? We cannot make new Java installs in the meantime...

**Comment by halcyon** [comment]
I appreciate the good work from @adyang. I'm in progress on some ideas that I think may be able to clean up our code base and resolve this issue at the same time. You can expect a resolution from me within the next day or so. Thank you again for all your help and bringing this problem to my attention.
