### ISSUE TITLE
Cannot install any versions of Java: unbound variable error

### ISSUE THREAD

**Issue by soggycactus** [halcyon/asdf-java#78]
I can't seem to install any versions of Java, I've tried to install multiple different versions of Java on two different machines using asdf and I keep getting the same error. 

I most recently ran `asdf install java adopt-openjdk-9.0.4+12_openj9-0.9.0` and got back:

    /Users/lucasstephens/.asdf/plugins/java/bin/install: line 155: package[0]: unbound variable

**Comment by halcyon** [comment]
If you use the gitter link, I can help you.

**Comment by soggycactus** [comment]
Resolved by 1b6aaee2ea27033033e93af7cb5431ff8da2ba10

Thanks so much!! @halcyon
