### ISSUE TITLE
mac_hotspot intalls not working

### ISSUE THREAD

**Issue by StefanoDeVuono** [halcyon/asdf-java#9]
We're missing a case statement in the `unpack_java` function. I'm going to add a PR to fix this.

**Comment by StefanoDeVuono** [comment]
https://github.com/halcyon/asdf-java/pull/10

**Comment by halcyon** [comment]
I very much appreciate the PR. Could you please take a quick look at https://github.com/halcyon/asdf-java-2 ? I'm planning to completely replace the asdf-java plugin with this rewrite.
