### ISSUE TITLE
Error when PROMPT_COMMAND already ends with semicolon

### ISSUE THREAD

**Issue by janpieper** [halcyon/asdf-java#91]
When using [direnv](https://github.com/direnv/direnv) and `set-java-home.bash`, the `PROMPT_COMMAND` will be set to:

```bash
_direnv_hook;; prompt_command
```

This causes bash to cry, because it does not like `;;` :cry: 

```
-bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 0: `_direnv_hook;; prompt_command'        
```

I thought of checking whether `PROMPT_COMMAND` already ends with `;` to avoid adding another `;`, but I am not a bash expert. Maybe there is a better way to solve this issue.

I am currently using this as a workaround:

```bash
export PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND} :}"

. ~/.asdf/plugins/java/set-java-home.sh
```

`PROMPT_COMMAND` will be set to `_direnv_hook; :; prompt_command`. See [this comment](https://stackoverflow.com/a/3224910/9858139) at Stackoverflow to understand what `:` stands for.

**Comment by olbrich** [comment]
@janpieper I had a similar problem and tried adding asdf before direnv in my .bash_profile and that seems to have worked. YMMV

**Comment by onionhead0708** [comment]
I got the same issue when using the powerline. i to put the asdf config before the powerline config in the .bashrc (as @olbrich  mentioned) and worked.

**Comment by jinmiaoluo** [comment]
My `PROMPT_COMMAND` variable:

```shell
_direnv_hook;(_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &); asdf_java_prompt_command;
```

How [direnv](https://github.com/direnv/direnv) deals with PROMPT_COMMAND
variable:

```shell
_direnv_hook() {
  local previous_exit_status=$?;
  trap -- '' SIGINT;
  eval "$("/usr/bin/direnv" export bash)";
  trap - SIGINT;
  return $previous_exit_status;
};
if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
```

direnv will add `_direnv_hook;` before the old content in PROMPT_COMMAND
variable.

How command [z](https://github.com/rupa/z) deals with PROMPT_COMMAND variable:

```shell
[ "$_Z_NO_PROMPT_COMMAND" ] || {
# populate directory list. avoid clobbering other PROMPT_COMMANDs.
  grep "_z --add" <<< "$PROMPT_COMMAND" >/dev/null || {
    PROMPT_COMMAND="$PROMPT_COMMAND"$'\n''(_z --add "$(command pwd '$_Z_RESOLVE_SYMLINKS' 2>/dev/null)" 2>/dev/null &);'
  }
}
```

command z will add `(_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &);`
after the old content in PROMPT_COMMAND variable with `;` suffix.

How can I fix this question?

change your `.bashrc`, let asdf java bash script `source` first, before direnv
and command z(and any other commands will change PROMPT_COMMAND variable).

or:

let command z `source` first, and then use the patch in my MR,  and then `source` the asdf java home bash script.

**Comment by jinmiaoluo** [comment]
Maybe we can change [set-java-home.bash](https://github.com/halcyon/asdf-java/blob/master/set-java-home.bash) to:

```
if ! [[ "${PROMPT_COMMAND:-}" =~ prompt_command ]]; then
  PROMPT_COMMAND="prompt_command${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
```

**Comment by jinmiaoluo** [comment]
BTW, we should use  `_asdf_java_prompt_command` instead of `prompt_command`, which would be more specific to describe it.
